import { Grid } from "@mui/material";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function AuthLayout({ children }) {
    return (
        <Grid container alignItems="center" justifyContent={"center"} sx={{ height: '100vh' }}>
            <Grid item xs={8}>{children}</Grid>
        </Grid>
    );
}